/* Populate database with sample data. */

INSERT INTO animals VALUES (1, 'Agumon', '03-02-2020', 0, TRUE, 10.23)
INSERT INTO animals VALUES (2, 'Gabumon', '15-11-2018', 2, TRUE, 8)
INSERT INTO animals VALUES (3, 'Pikachu', '07-01-2021', 1, FALSE, 15.04)
INSERT INTO animals VALUES (4, 'Devimon', '12-06-2017', 5, TRUE, 11)

INSERT INTO animals (id,name, date_of_birth, escape_attempts, neutered, weight_kg) VALUES        
        (5,'Charmander', '2022-02-08', 0, 'FALSE', -11),
        (6,'Plantmon', '2021-11-15', 2, 'TRUE', -5.7), 
        (7,'Squirtle', '1993-04-02', 3, 'FALSE', -12.13), 
        (8,'Angemon', '2005-06-12', 1, 'TRUE', -45),
        (9,'Boarmon', '2005-06-07', 7, 'TRUE', 20.4), 
        (10,'Blossom', '1998-08-13', 3, 'TRUE', 17), 
        (11,'Ditto', '2022-05-14', 4, 'TRUE', 22)
;


/*Create a table named owners*/

CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    full_name CHAR(150), 
    age INT
);
ALTER TABLE owners ADD PRIMARY KEY (id);

/*Create a table named species*/

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    name CHAR(150)
);
ALTER TABLE species ADD PRIMARY KEY (id);


/*Remove column species from animals table*/

  ALTER TABLE animals DROP COLUMN species;

  /*Add column species_id which is a foreign key referencing species table*/

  ALTER TABLE animals ADD COLUMN species_ID INT;
  ALTER TABLE animals ADD FOREIGN KEY (species_ID) REFERENCES species(id);  

  /*Add column owner_id which is a foreign key referencing the owners table*/  

  ALTER TABLE animals ADD COLUMN owners_ID INT;
  ALTER TABLE animals ADD FOREIGN KEY (owners_ID) REFERENCES owners(id);