CREATE TABLE animals (
    id INT, 
    name CHAR(24), 
    date_of_birth DATE, 
    escape_attempts INT, 
    neutered BOOLEAN, 
    weight_kg DECIMAL)

ALTER TABLE animals ADD species varchar(255);

/*Create a table named owners*/

CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    full_name CHAR(150), 
    age INT
);
ALTER TABLE owners ADD PRIMARY KEY (id);

/*Create a table named species*/

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    name CHAR(150)
);
ALTER TABLE species ADD PRIMARY KEY (id);


/*Remove column species from animals table*/

ALTER TABLE animals DROP COLUMN species;

/*Add column species_id which is a foreign key referencing species table*/

ALTER TABLE animals ADD COLUMN species_ID INT;
ALTER TABLE animals ADD FOREIGN KEY (species_ID) REFERENCES species(id);  

/*Add column owner_id which is a foreign key referencing the owners table*/  

ALTER TABLE animals ADD COLUMN owners_ID INT;
ALTER TABLE animals ADD FOREIGN KEY (owners_ID) REFERENCES owners(id);


/*Create vets table*/

CREATE TABLE vets (
    id INT GENERATED ALWAYS AS IDENTITY, 
    name CHAR(75), age INT, 
    date_of_graduation DATE, 
    PRIMARY KEY(id)
);

/*Create table specializations */

CREATE TABLE specializations (
    vets_id INT REFERENCES vets(id) , 
    species_id INT REFERENCES species(id), 
);

/*Create a "join table" called visits*/

CREATE TABLE visits (
    animals_id INT REFERENCES animals(id), 
    vets_id INT REFERENCES vets(id),
    date_of_visits DATE, 
);